name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
      
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v3
        with: 
            owner: namrata-org-1
            repo: new-pkg-public
            package-name: new-pkg-public-with-repo
            num-old-versions-to-delete: 1
            token: ${{ secrets.READ_WRITE_PACKAGES_TOKEN }}
            

 


          